import Link from "next/link";
import React from "react";

export const metadata = {
    title: "Sobre",
    description: "Generated by create next app",
  };
  

export default function AboutPage() {
  return (
    <div className="text-black">
      <h1 >About Page</h1>
    </div>
  );
}
