import Link from "next/link";
import React from "react";
import Menu from "@/components/Menu";

export const metadata = {
  title: "Contato",
  description: "Generated by create next app",
};

export default function ContactPage() {
  return (
    <div className="text-black">
      <h1>Contact Page</h1>
    </div>
  );
}
