import "./globals.css";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Portifolio",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin-ext"],
  weight: "400",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
