import Navegation from "@/components/Navegation";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin-ext"],
  weight: "400",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navegation>{children}</Navegation>
        <Footer />
      </body>
    </html>
  );
}
